name: flutter_gx_gam
description: Librería en Flutter que integra la login, autenticación y autorización con GAM
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  http_extensions_cache: ^0.1.3
  shared_preferences: ^0.5.7+3
  validators_helper:
    git:
      url:  git://github.com/thelabs-dev/validators-helper.dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter
