name: flutter_gx_gam
description: Librería en Flutter que integra la login, autenticación y autorización con GAM
version: 0.2.0
author: Francisco Crizul
homepage: https://github.com/fcrizul

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  http_extensions_cache: ^0.1.3
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
